language: java
jdk:
  - oraclejdk8
before_install:
  - git clone https://github.com/caarlos0/guice-junit-test-runner.git
  - mvn clean install -f guice-junit-test-runner/pom.xml
script: mvn clean install -Pqulice

